In [21]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt
import os

In [22]:
current_dir = os.getcwd()

# current_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(current_dir, "..", "Data", "bigfive_data.csv")
csv_path = os.path.abspath(csv_path)

In [23]:
data_raw=pd.read_csv(csv_path,delimiter='\t')
data_raw.info

<bound method DataFrame.info of          EXT1  EXT2  EXT3  EXT4  EXT5  ...  endelapse  IPC  country  \
0         4.0   1.0   5.0   2.0   5.0  ...          6    1       GB
1         3.0   5.0   3.0   4.0   3.0  ...         11    1       MY
2         2.0   3.0   4.0   4.0   3.0  ...          7    1       GB
3         2.0   2.0   2.0   3.0   4.0  ...          7    1       GB
4         3.0   3.0   3.0   3.0   5.0  ...         17    2       KE
...       ...   ...   ...   ...   ...  ...        ...  ...      ...
1015336   4.0   2.0   4.0   3.0   4.0  ...         10    2       US
1015337   4.0   3.0   4.0   3.0   3.0  ...          7    1       US
1015338   4.0   2.0   4.0   3.0   5.0  ...         12    6       US
1015339   2.0   4.0   3.0   4.0   2.0  ...          8    1       US
1015340   4.0   2.0   4.0   2.0   4.0  ...          9    1       US

         lat_appx_lots_of_err  long_appx_lots_of_err
0                     51.5448                 0.1991
1                      3.1698                101.706
2                     54.9119                -1.3833
3                       51.75                  -1.25
4                         1.0                   38.0
...                       ...                    ...
1015336               39.9883               -75.2208
1015337                  38.0                  -97.0
1015338               36.1473                -86.777
1015339               34.1067              -117.8067
1015340                  38.0                  -97.0

[1015341 rows x 110 columns]>

In [24]:
data = data_raw.copy()
pd.options.display.max_columns = 150
data.drop(data.columns[50:107], axis=1, inplace=True)
data.drop(data.columns[51:], axis=1, inplace=True)
print('Number of participants: ', len(data))
data.head()

Number of participants:  1015341

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,EST1,EST2,EST3,EST4,EST5,EST6,EST7,EST8,EST9,EST10,AGR1,AGR2,AGR3,AGR4,AGR5,AGR6,AGR7,AGR8,AGR9,AGR10,CSN1,CSN2,CSN3,CSN4,CSN5,CSN6,CSN7,CSN8,CSN9,CSN10,OPN1,OPN2,OPN3,OPN4,OPN5,OPN6,OPN7,OPN8,OPN9,OPN10,country
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,5.0,2.0,4.0,2.0,3.0,2.0,4.0,3.0,4.0,3.0,4.0,3.0,2.0,2.0,4.0,4.0,2.0,4.0,4.0,5.0,1.0,4.0,1.0,4.0,1.0,5.0,3.0,4.0,5.0,GB
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,2.0,3.0,4.0,1.0,3.0,1.0,2.0,1.0,3.0,1.0,1.0,4.0,1.0,5.0,1.0,5.0,3.0,4.0,5.0,3.0,3.0,2.0,5.0,3.0,3.0,1.0,3.0,3.0,5.0,3.0,1.0,2.0,4.0,2.0,3.0,1.0,4.0,2.0,5.0,3.0,MY
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,4.0,4.0,4.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,4.0,1.0,4.0,2.0,4.0,1.0,4.0,4.0,3.0,4.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,4.0,2.0,5.0,1.0,2.0,1.0,4.0,2.0,5.0,3.0,4.0,4.0,GB
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,3.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,4.0,3.0,2.0,4.0,3.0,4.0,2.0,4.0,2.0,4.0,3.0,4.0,2.0,4.0,4.0,4.0,1.0,2.0,2.0,3.0,1.0,4.0,4.0,2.0,5.0,2.0,3.0,1.0,4.0,4.0,3.0,3.0,GB
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,1.0,5.0,5.0,3.0,1.0,1.0,1.0,1.0,3.0,2.0,1.0,5.0,1.0,5.0,1.0,3.0,1.0,5.0,5.0,3.0,5.0,1.0,5.0,1.0,3.0,1.0,5.0,1.0,5.0,5.0,5.0,1.0,5.0,1.0,5.0,1.0,5.0,3.0,5.0,5.0,KE

In [25]:
data = data.drop(columns = ['EXT6','EXT9','EXT10','EST5','EST8','EST9','EST10','AGR5','AGR7','AGR9','CSN3','CSN5','OPN4','OPN5','OPN6','OPN8','OPN9'])
data[['EXT2','EXT4','EXT8','EST2','EST4','AGR1','AGR3','CSN2','CSN4','CSN6','CSN8']] = -data[['EXT2','EXT4','EXT8','EST2','EST4','AGR1','AGR3','CSN2','CSN4','CSN6','CSN8']]

In [26]:
data

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT7,EXT8,EST1,EST2,EST3,EST4,EST6,EST7,AGR1,AGR2,AGR3,AGR4,AGR6,AGR8,AGR10,CSN1,CSN2,CSN4,CSN6,CSN7,CSN8,CSN9,CSN10,OPN1,OPN2,OPN3,OPN7,OPN10,country
0,4.0,-1.0,5.0,-2.0,5.0,5.0,-2.0,1.0,-4.0,4.0,-2.0,2.0,2.0,-2.0,5.0,-2.0,4.0,3.0,4.0,4.0,3.0,-4.0,-2.0,-4.0,4.0,-2.0,4.0,4.0,5.0,1.0,4.0,5.0,5.0,GB
1,3.0,-5.0,3.0,-4.0,3.0,2.0,-5.0,2.0,-3.0,4.0,-1.0,1.0,2.0,-1.0,4.0,-1.0,5.0,5.0,4.0,3.0,3.0,-2.0,-3.0,-1.0,3.0,-3.0,5.0,3.0,1.0,2.0,4.0,4.0,3.0,MY
2,2.0,-3.0,4.0,-4.0,3.0,1.0,-3.0,4.0,-4.0,4.0,-2.0,2.0,2.0,-1.0,4.0,-1.0,4.0,4.0,4.0,3.0,4.0,-2.0,-2.0,-3.0,4.0,-2.0,4.0,2.0,5.0,1.0,2.0,5.0,4.0,GB
3,2.0,-2.0,2.0,-3.0,4.0,2.0,-4.0,3.0,-3.0,3.0,-2.0,2.0,2.0,-2.0,4.0,-3.0,4.0,4.0,4.0,4.0,2.0,-4.0,-4.0,-2.0,2.0,-3.0,1.0,4.0,4.0,2.0,5.0,4.0,3.0,GB
4,3.0,-3.0,3.0,-3.0,5.0,3.0,-5.0,1.0,-5.0,5.0,-3.0,1.0,1.0,-1.0,5.0,-1.0,5.0,3.0,5.0,3.0,5.0,-1.0,-1.0,-1.0,5.0,-1.0,5.0,5.0,5.0,1.0,5.0,5.0,5.0,KE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015336,4.0,-2.0,4.0,-3.0,4.0,3.0,-3.0,4.0,-3.0,3.0,-3.0,3.0,4.0,-5.0,4.0,-2.0,5.0,4.0,4.0,4.0,2.0,-3.0,-3.0,-4.0,4.0,-2.0,3.0,3.0,2.0,2.0,4.0,4.0,4.0,US
1015337,4.0,-3.0,4.0,-3.0,3.0,4.0,-4.0,4.0,-3.0,5.0,-1.0,5.0,4.0,-2.0,4.0,-1.0,4.0,5.0,3.0,3.0,3.0,-2.0,-4.0,-3.0,2.0,-3.0,2.0,3.0,4.0,1.0,5.0,3.0,4.0,US
1015338,4.0,-2.0,4.0,-3.0,5.0,4.0,-2.0,3.0,-2.0,4.0,-3.0,2.0,4.0,-3.0,5.0,-5.0,3.0,3.0,4.0,5.0,4.0,-5.0,-5.0,-5.0,1.0,-4.0,1.0,4.0,5.0,1.0,5.0,5.0,5.0,US
1015339,2.0,-4.0,3.0,-4.0,2.0,1.0,-4.0,4.0,-3.0,4.0,-2.0,4.0,2.0,-2.0,3.0,-2.0,4.0,4.0,4.0,3.0,4.0,-2.0,-2.0,-2.0,4.0,-2.0,4.0,4.0,5.0,2.0,4.0,4.0,3.0,US
1015340,4.0,-2.0,4.0,-2.0,4.0,4.0,-2.0,4.0,-3.0,4.0,-3.0,3.0,3.0,-1.0,5.0,-2.0,4.0,5.0,3.0,5.0,3.0,-4.0,-3.0,-3.0,3.0,-2.0,2.0,3.0,5.0,1.0,5.0,5.0,5.0,US

In [27]:
df = data.drop('country', axis=1)

In [28]:
# # For ease of calculation lets scale all the values between 0-1 and take a sample of 5000 
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import joblib

columns = list(df.columns)

scaler = MinMaxScaler()
df = scaler.fit_transform(df)
df = pd.DataFrame(df, columns=columns)
# This (scaler ) is created just for sake of ease of calculation for clustering 
df = df.dropna(axis=0)
df_sample = df

In [ ]:
root_dir = os.path.abspath(os.path.join(current_dir, "..","artifacts"))
joblib.dump(scaler, os.path.join(root_dir, 'bigfive_scaler.pkl'))

['c:\\Users\\usEr\\Documents\\GitHub\\Career-path-guidance-web-application\\ML\\bigfive_scaler.pkl']

In [31]:
# Creating K-means Cluster Model
from sklearn.cluster import KMeans

n_label = 8
result = []
n_runs = 100

traits = {
    'Extroversion': ['EXT1', 'EXT2', 'EXT3', 'EXT4', 'EXT5',  'EXT7', 'EXT8'],
    'Agreeableness': ['AGR1', 'AGR2', 'AGR3', 'AGR4',  'AGR6',  'AGR8',  'AGR10'],
    'Conscientiousness': ['CSN1', 'CSN2',  'CSN4',  'CSN6', 'CSN7', 'CSN8', 'CSN9', 'CSN10'],
    'Neuroticism': ['EST1', 'EST2', 'EST3', 'EST4',  'EST6', 'EST7'],
    'Openness': ['OPN1', 'OPN2', 'OPN3',  'OPN7',  'OPN10']
}

for run in range(n_runs):
    # I define 5 clusters and fit my model
    kmeans = KMeans(n_clusters=n_label)
    k_fit = kmeans.fit(df_sample)

    # Predicting the Clusters
    pd.options.display.max_columns = 10

    #labels_ is used to identify Labels of each point
    predictions = k_fit.labels_
    df_sample['Clusters'] = predictions
    # df_sample.head(10)

In [32]:
df_sample.head(10)

   EXT1  EXT2  EXT3  EXT4  EXT5  ...  OPN2  OPN3  OPN7  OPN10  Clusters
0   0.8   0.8   1.0   0.6   1.0  ...   0.2   0.8   1.0    1.0         7
1   0.6   0.0   0.6   0.2   0.6  ...   0.4   0.8   0.8    0.6         2
2   0.4   0.4   0.8   0.2   0.6  ...   0.2   0.4   1.0    0.8         4
3   0.4   0.6   0.4   0.4   0.8  ...   0.4   1.0   0.8    0.6         6
4   0.6   0.4   0.6   0.4   1.0  ...   0.2   1.0   1.0    1.0         4
5   0.6   0.4   0.8   0.6   0.8  ...   0.2   1.0   1.0    0.4         4
6   0.8   0.4   0.8   0.4   0.6  ...   0.4   0.8   1.0    0.8         7
7   0.6   0.8   1.0   0.6   1.0  ...   0.2   0.6   0.8    1.0         4
8   0.4   0.6   0.6   0.4   0.8  ...   0.2   1.0   1.0    1.0         6
9   0.2   0.0   0.6   0.0   0.4  ...   0.2   0.6   0.8    0.6         3

[10 rows x 34 columns]

In [33]:
value_counts = df_sample['Clusters'].value_counts()
print(value_counts)

Clusters
2    259351
4    182316
6    154454
1    103865
5     96351
3     88441
7     80916
0     47864
Name: count, dtype: int64

In [38]:
df_sample

         EXT1  EXT2  EXT3  EXT4  EXT5  ...  OPN2  OPN3  OPN7  OPN10  Clusters
0         0.8   0.8   1.0   0.6   1.0  ...   0.2   0.8   1.0    1.0         7
1         0.6   0.0   0.6   0.2   0.6  ...   0.4   0.8   0.8    0.6         2
2         0.4   0.4   0.8   0.2   0.6  ...   0.2   0.4   1.0    0.8         4
3         0.4   0.6   0.4   0.4   0.8  ...   0.4   1.0   0.8    0.6         6
4         0.6   0.4   0.6   0.4   1.0  ...   0.2   1.0   1.0    1.0         4
...       ...   ...   ...   ...   ...  ...   ...   ...   ...    ...       ...
1015336   0.8   0.6   0.8   0.4   0.8  ...   0.4   0.8   0.8    0.8         6
1015337   0.8   0.4   0.8   0.4   0.6  ...   0.2   1.0   0.6    0.8         1
1015338   0.8   0.6   0.8   0.4   1.0  ...   0.2   1.0   1.0    1.0         6
1015339   0.4   0.2   0.6   0.2   0.4  ...   0.4   0.8   0.8    0.6         2
1015340   0.8   0.6   0.8   0.6   0.8  ...   0.2   1.0   1.0    1.0         7

[1013558 rows x 34 columns]

In [42]:
current_dir = os.getcwd()
csv_dir = os.path.abspath(os.path.join(current_dir, "..", "Data"))  # Path to folder
csv_path = os.path.join(csv_dir, "label_data_bigfive.csv")          # Full path with filename

df_sample.to_csv(csv_path, index=False)
print("Saved CSV to:", csv_path)

Saved CSV to: c:\Users\usEr\Documents\GitHub\Career-path-guidance-web-application\ML\Data\label_data_bigfive.csv

In [35]:
 # คำนวณค่าเฉลี่ยในแต่ละกลุ่ม
cluster_trait_means = {}
for trait, columns in traits.items():
    cluster_trait_means[trait] = df_sample[columns].mean(axis=1).groupby(df_sample['Clusters']).mean()


# สร้าง DataFrame แสดงค่าเฉลี่ย
cluster_means = pd.DataFrame(cluster_trait_means)

cluster_means.index = range(n_label)

# Convert the DataFrame to a numpy array
array = cluster_means.values.T  # Transpose to have clusters as columns and traits as rows

result.append(array)
# print(cluster_means)

In [36]:
df_sample

df.head(5)

   EXT1  EXT2  EXT3  EXT4  EXT5  ...  OPN2  OPN3  OPN7  OPN10  Clusters
0   0.8   0.8   1.0   0.6   1.0  ...   0.2   0.8   1.0    1.0         7
1   0.6   0.0   0.6   0.2   0.6  ...   0.4   0.8   0.8    0.6         2
2   0.4   0.4   0.8   0.2   0.6  ...   0.2   0.4   1.0    0.8         4
3   0.4   0.6   0.4   0.4   0.8  ...   0.4   1.0   0.8    0.6         6
4   0.6   0.4   0.6   0.4   1.0  ...   0.2   1.0   1.0    1.0         4

[5 rows x 34 columns]

In [37]:
average_values = np.mean(result, axis=0)

df_result = pd.DataFrame(average_values)
df_result.index = ['Extroversion', 'Agreeableness', 'Conscientiousness', 'Neuroticism', 'Openness']
df_result.columns = [f'Clusters {i}' for i in range(n_label)]

df_result

,Clusters 0,Clusters 1,Clusters 2,Clusters 3,Clusters 4,Clusters 5,Clusters 6,Clusters 7
Extroversion,0.694595,0.658867,0.342288,0.340631,0.596521,0.335082,0.567753,0.766270
Agreeableness,0.576614,0.777025,0.730386,0.482822,0.777411,0.544243,0.659237,0.819977
Conscientiousness,0.536415,0.471296,0.575987,0.449693,0.735175,0.624044,0.481273,0.606244
Neuroticism,0.365558,0.719933,0.686178,0.670380,0.483011,0.425231,0.535786,0.489809
Openness,0.729898,0.736481,0.703547,0.623267,0.717858,0.702397,0.698261,0.751116

In [19]:
categories = ["Extroversion", "Agreeableness", "Conscientiousness", "Neuroticism", "Openness"]
df = pd.DataFrame(df_result, index=categories)

scaled_df = df.apply(lambda row: (row - row.min()) / (row.max() - row.min()), axis=1)

scaled_df

,Clusters 0,Clusters 1,Clusters 2,Clusters 3,Clusters 4,Clusters 5,Clusters 6,Clusters 7
Extroversion,0.000000,0.913233,0.912326,0.184015,0.716978,1.0,0.429226,0.185694
Agreeableness,0.828597,0.952153,0.988854,0.000000,0.739394,1.0,0.676132,0.728981
Conscientiousness,0.000000,0.647166,0.129680,0.448354,0.430555,1.0,0.513213,0.723294
Neuroticism,1.000000,0.377849,0.861636,0.354621,0.955014,0.0,0.363870,0.804173
Openness,0.862419,0.792969,0.982194,0.575240,0.675016,1.0,0.000000,0.532283